//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMBEDConfig.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ja_JP {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ja_JP() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AMBEDConfig.Properties.ja-JP", typeof(ja_JP).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to キャンセル.
        /// </summary>
        internal static string button_cancel {
            get {
                return ResourceManager.GetString("button_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string button_OK {
            get {
                return ResourceManager.GetString("button_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USB LANアダプタを使用(&amp;U).
        /// </summary>
        internal static string checkBox_useUSB {
            get {
                return ResourceManager.GetString("checkBox_useUSB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ルーターアドレスの値が不正です.
        /// </summary>
        internal static string error_routerAddr2 {
            get {
                return ResourceManager.GetString("error_routerAddr2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USB LANルーターアドレスの値が不正です.
        /// </summary>
        internal static string error_routerAddr4 {
            get {
                return ResourceManager.GetString("error_routerAddr4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to サブネットマスクは16以上の値です.
        /// </summary>
        internal static string error_subnet16 {
            get {
                return ResourceManager.GetString("error_subnet16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to サブネットマスクは24以上の値です.
        /// </summary>
        internal static string error_subnet24 {
            get {
                return ResourceManager.GetString("error_subnet24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to サブネットマスクは8以上の値です.
        /// </summary>
        internal static string error_subnet8 {
            get {
                return ResourceManager.GetString("error_subnet8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 固定IPアドレス.
        /// </summary>
        internal static string fld_ipAddr1 {
            get {
                return ResourceManager.GetString("fld_ipAddr1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ルーターIPアドレス.
        /// </summary>
        internal static string fld_routerAddr2 {
            get {
                return ResourceManager.GetString("fld_routerAddr2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WiFi設定.
        /// </summary>
        internal static string groupBox1 {
            get {
                return ResourceManager.GetString("groupBox1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 有線 LAN 設定 (USB LAN アダプタを使用する場合のみ).
        /// </summary>
        internal static string groupBox2 {
            get {
                return ResourceManager.GetString("groupBox2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to その他の設定.
        /// </summary>
        internal static string groupBox3 {
            get {
                return ResourceManager.GetString("groupBox3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XRFリフレクター同好会 Copyright (c) 2018.
        /// </summary>
        internal static string label_about {
            get {
                return ResourceManager.GetString("label_about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AMBEポート番号(&amp;A).
        /// </summary>
        internal static string label_ambePort {
            get {
                return ResourceManager.GetString("label_ambePort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 国コード(&amp;C).
        /// </summary>
        internal static string label_countryCode {
            get {
                return ResourceManager.GetString("label_countryCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 固定IPアドレス(&amp;I).
        /// </summary>
        internal static string label_ipAddr1 {
            get {
                return ResourceManager.GetString("label_ipAddr1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 固定IPアドレス(&amp;P).
        /// </summary>
        internal static string label_ipAddr3 {
            get {
                return ResourceManager.GetString("label_ipAddr3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WiFiパスワード(&amp;K).
        /// </summary>
        internal static string label_keyPhrase {
            get {
                return ResourceManager.GetString("label_keyPhrase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ポータブル AMBEサーバー.
        /// </summary>
        internal static string label_prodName {
            get {
                return ResourceManager.GetString("label_prodName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ルーターアドレス(&amp;R).
        /// </summary>
        internal static string label_routerAddr2 {
            get {
                return ResourceManager.GetString("label_routerAddr2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ルーターアドレス(&amp;O).
        /// </summary>
        internal static string label_routerAddr4 {
            get {
                return ResourceManager.GetString("label_routerAddr4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSHポート番号(&amp;S).
        /// </summary>
        internal static string label_sshPort {
            get {
                return ResourceManager.GetString("label_sshPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSID(&amp;S).
        /// </summary>
        internal static string label_ssid {
            get {
                return ResourceManager.GetString("label_ssid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (設定ソフトウェア V {0}).
        /// </summary>
        internal static string label_version {
            get {
                return ResourceManager.GetString("label_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WiFiセキュリティ(&amp;W).
        /// </summary>
        internal static string label_wifiType {
            get {
                return ResourceManager.GetString("label_wifiType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ポータブル AMBEサーバー 設定.
        /// </summary>
        internal static string programTitle {
            get {
                return ResourceManager.GetString("programTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ポータブルAMBEサーバーに割り当てる固定IPアドレス.
        /// </summary>
        internal static string tag_ipAddr1_1 {
            get {
                return ResourceManager.GetString("tag_ipAddr1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ルーターまたは携帯電話のIPアドレス.
        /// </summary>
        internal static string tag_ipAddr2_1 {
            get {
                return ResourceManager.GetString("tag_ipAddr2_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WiFiのSSIDを入力してください.
        /// </summary>
        internal static string tag_ssid {
            get {
                return ResourceManager.GetString("tag_ssid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright (c) 2018 by XRFリフレクタ同好会
        ///
        ///JR1OFP, JA1COU, JA4CXX, JH1TWX, JA3IYX,
        ///JA4DQX, JA4CFO, NW6UP (順不同).
        /// </summary>
        internal static string text_aboutUs {
            get {
                return ResourceManager.GetString("text_aboutUs", resourceCulture);
            }
        }
    }
}
